---
# file: roles/fabric-ca/tasks/main.yml
#
# file: make sure directories exists
- name: fabric-ca | make sure direcoties needed by fabric-ca exists
  file:
    path: "/hfc-data/{{ inventory_hostname_short | lower }}/{{ item }}/"
    state: directory
    owner: root
    group: root
    mode: 0644
  with_items:
    - restore
    - configtx

# copy: copy crypto for fabric-ca
- name: fabric-ca | copy crypto for fabric-ca
  copy:
    src: "{{ ca_org_id | lower }}/ca/"
    dest: /hfc-data/{{ inventory_hostname_short | lower }}/configtx/
    owner: root
    group: root
    mode: 0644

# template: copy env_file for fabric-ca
- name: fabric-ca | copy env_file for fabric-ca
  template: 
    src: env_file.j2
    dest: /hfc-data/{{ inventory_hostname_short | lower }}/restore/env_file

# docker_container: start containers of fabric-ca
- name: fabric-ca | launch fabric-ca
  docker_container:
    name: "{{ inventory_hostname_short | lower }}"
    hostname: "{{ inventory_hostname_short | lower }}"
    image: "{{ hfc_images.ca.tags.0 }}"
    env_file: /hfc-data/{{ inventory_hostname_short | lower }}/restore/env_file
    volumes:
      - /hfc-data/{{ inventory_hostname_short | lower }}/configtx/:/etc/hyperledger/configtx/{{ inventory_hostname_short | lower }}
    ports:
      - "0.0.0.0:{{ ca_expose_port }}:{{ ca_listen_port }}"
    dns_servers:
      - "{{ hostvars['dnsmasq_server'].ansible_host }}"
    command: fabric-ca-server start -b admin:adminpw
    state: started
    restart_policy: unless-stopped
    labels:
      org.jcloud.hyperledger: "fabric"
      org.jcloud.hyperledger.role: "fabric-ca"
  register: container_up

# blockinfile: generate restore script for fabric-ca
- name: fabric-ca | generate restore script for fabric-ca
  template: 
    src: run_new.sh.j2
    dest: /hfc-data/{{ inventory_hostname_short | lower }}/restore/run-{{ inventory_hostname_short | lower }}.sh
    mode: 0755
  
# cron: setup cron jobs for backup of fabric-ca
- name: fabric-ca | setup cron jobs for backup of fabric-ca
  cron:
    name: backup /hfc-data/{{ inventory_hostname_short | lower }}
    minute: "{{ ( inventory_hostname_short | hash | list | map('int',0,16) | sum ) % 60 }}"
    hour: "{{ (( inventory_hostname_short | hash | list | map('int',0,16) | sum ) % 2) + 1 }}"
    user: root
    job: "/usr/local/bin/fabric-backup.sh {{ inventory_hostname_short | lower }}"
    cron_file: "{{ inventory_hostname_short | lower }}-backup"
