---
# file: roles/couchdb/tasks/main.yml
#
# file: make sure directories exists
- name: couchdb | make sure direcoties needed by fabric-couchdb exists
  file:
    path: "/hfc-data/{{ inventory_hostname_short | lower }}/{{ item }}/"
    state: directory
    owner: root
    group: root
    mode: 0644
  with_items:
    - restore
    - data

# template: copy env_file for fabric-couchdb
- name: couchdb | copy env_file for fabric-couchdb
  template: 
    src: env_file.j2
    dest: /hfc-data/{{ inventory_hostname_short | lower }}/restore/env_file

# docker_container: launch fabric-couchdb
- name: couchdb | launch fabric-couchdb
  docker_container:
    name: "{{ inventory_hostname_short | lower }}"
    hostname: "{{ inventory_hostname_short | lower }}"
    image: "{{ hfc_images.couchdb.tags.0 }}"
    env_file: /hfc-data/{{ inventory_hostname_short | lower }}/restore/env_file
    ports:
      - "0.0.0.0:{{ couchdb_expose_port }}:{{ couchdb_listen_port }}"
    dns_servers:
      - "{{ hostvars['dnsmasq_server'].ansible_host }}"
    state: started
    restart_policy: unless-stopped
    labels:
      org.jcloud.hyperledger: "fabric"
      org.jcloud.hyperledger.role: "fabric-couchdb"
  register: container_up
