---
# file: roles/mon-nodeexporter/tasks/main.yml
#
# docker-image: pull image from the list
- name: mon-nodeexporter | pull docker images
  docker_image:
    name: "{{ nodeexporter_image }}"
    state: present

#
# nodeexporter
#
# docker-container: run nodeexporter
- name: mon-nodeexporter | run nodeexporter
  docker_container:
    name: nodeexporter
    hostname: nodeexporter
    image: "{{ nodeexporter_image }}"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "{{ nodeexporter_expose_port }}:9100"
    network_mode: host
    dns_servers:
      - "{{ hostvars['dnsmasq1'].ansible_host }}"
      - "{{ hostvars['dnsmasq2'].ansible_host }}"
    labels:
      com.jcloud.group: "monitoring"
      com.jcloud.nodetype: "nodeexporter"
    restart_policy: always
    restart: yes
    state: started