---
# file: prod.yml
- name: Run roles - common
  hosts: all
  roles:
    - common

- name: Run roles - couchdb | couchdb1
  hosts: fabric-aio
  roles:
    - { role: couchdb, couchdb_node_id: couchdb1 }

- name: Run roles - fabric-ca | peerOrg1
  hosts: fabric-aio
  roles:
    - { role: fabric-ca, ca_listen_port: 7054, ca_expose_port: 7054, ca_org_id: peerOrg1 }

- name: Run roles - fabric-ca | peerOrg2
  hosts: fabric-aio
  roles:
    - { role: fabric-ca, ca_listen_port: 7054, ca_expose_port: 8054, ca_org_id: peerOrg2 }

- name: Run roles - fabric-orderer | ordererOrg1
  hosts: fabric-aio
  roles:
    - { role: fabric-orderer, orderer_msp_id: OrdererMSP, orderer_org_id: ordererOrg1 }

- name: Run roles - fabric-peer | peer1
  hosts: fabric-aio
  roles:
    - { role: fabric-peer, peer_node_id: peer1, peer_org_id: peerOrg1, peer_msp_id: Org1MSP, peer_expose_listen_port: 7051, peer_expose_events_port: 7053, orderer_expose_ip: 192.168.10.16, couchdb_expose_ip: 192.168.10.16, peer_gossip_ip: 192.168.10.16,     peer_gossip_port: 7051, peer_gossip_expose_port: 7051, peer_gossip_orgleader: true }

- name: Run roles - fabric-peer | peer2
  hosts: fabric-aio
  roles:
    - { role: fabric-peer, peer_node_id: peer2, peer_org_id: peerOrg1, peer_msp_id: Org1MSP, peer_expose_listen_port: 7056, peer_expose_events_port: 7058, orderer_expose_ip: 192.168.10.16, couchdb_expose_ip: 192.168.10.16, peer_gossip_ip: 192.168.10.16,     peer_gossip_port: 7051, peer_gossip_expose_port: 7056, peer_gossip_orgleader: false }

- name: Run roles - fabric-peer | peer3
  hosts: fabric-aio
  roles:
    - { role: fabric-peer, peer_node_id: peer3, peer_org_id: peerOrg2, peer_msp_id: Org2MSP, peer_expose_listen_port: 8051, peer_expose_events_port: 8053, orderer_expose_ip: 192.168.10.16, couchdb_expose_ip: 192.168.10.16, peer_gossip_ip: 192.168.10.16,     peer_gossip_port: 7051, peer_gossip_expose_port: 8051, peer_gossip_orgleader: true }

- name: Run roles - fabric-peer | peer4
  hosts: fabric-aio
  roles:
    - { role: fabric-peer, peer_node_id: peer4, peer_org_id: peerOrg2, peer_msp_id: Org2MSP, peer_expose_listen_port: 8056, peer_expose_events_port: 8058, orderer_expose_ip: 192.168.10.16, couchdb_expose_ip: 192.168.10.16, peer_gossip_ip: 192.168.10.16,     peer_gossip_port: 7051, peer_gossip_expose_port: 8056, peer_gossip_orgleader: false }
