---
# file: roles/mon-grafana/tasks/main.yml
#
# docker-image: pull image from the list
- name: mon-grafana | pull docker images
  docker_image:
    name: "{{ grafana_image }}"
    state: present

# make sure directories exists
- name: mon-grafana | make sure direcoties needed by mon-grafana exists
  file:
    path: "/monitor-server/grafana/{{ item }}/"
    state: directory
    owner: root
    group: root
    mode: 0644
  with_items:
    - data

#
# grafana
#
# docker-container: run grafana
- name: mon-grafana | run grafana
  docker_container:
    name: "{{ inventory_hostname_short|lower|replace('-','_') }}"
    hostname: "{{ inventory_hostname_short|lower|replace('-','_') }}"
    image: "{{ grafana_image }}"
    volumes:
      - /monitor-server/grafana/data:/var/lib/grafana
    env:
      GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      GF_USERS_ALLOW_SIGN_UP: "{{ grafana_allow_sign_up }}"
    ports:
      - "{{ grafana_expose_port }}:3000"
    dns_servers:
      - "{{ hostvars['dnsmasq1'].ansible_host }}"
      - "{{ hostvars['dnsmasq2'].ansible_host }}"
    labels:
      com.jcloud.group: "monitoring"
      com.jcloud.nodetype: "grafana"
    restart_policy: unless-stopped
    restart: yes
    state: started
