---
# file: roles/fabric-peer/tasks/main.yml
# make sure directories exists
- name: fabric-peer | make sure direcoties needed by fabric-peer exists
  file:
    path: "/hfc-data/{{ inventory_hostname_short | lower }}/{{ item }}/"
    state: directory
    owner: root
    group: root
    mode: 0644
  with_items:
    - restore
    - configtx
    - data

# copy crypto files for fabric-peer
- name: fabric-peer | copy crypto for fabric-peer
  copy:
    src: "{{ peer_org_id | lower }}/peers/{{ inventory_hostname_short | lower }}/"
    dest: /hfc-data/{{ inventory_hostname_short | lower }}/configtx/
    owner: root
    group: root
    mode: 0644

# template: copy env_file for fabric-peer
- name: fabric-peer | copy env_file for fabric-peer
  template: 
    src: env_file.j2
    dest: /hfc-data/{{ inventory_hostname_short | lower }}/restore/env_file

# docker_container: start containers of fabric-peer
- name: fabric-peer | launch fabric-peer
  docker_container:
    name: "{{ inventory_hostname_short | lower }}"
    hostname: "{{ inventory_hostname_short | lower }}"
    image: "{{ hfc_images.peer.tags.0 }}"
    env_file: /hfc-data/{{ inventory_hostname_short | lower }}/restore/env_file
    volumes:
      - /var/run/:/host/var/run/
      - /hfc-data/{{ inventory_hostname_short | lower }}/configtx/:/etc/hyperledger/configtx/
      - /hfc-data/{{ inventory_hostname_short | lower }}/data/:/var/hyperledger/
    ports:
      - "0.0.0.0:{{ peer_expose_listen_port }}:{{ peer_listen_port }}"
      - "0.0.0.0:{{ peer_expose_events_port }}:{{ peer_events_port }}"
    dns_servers:
      - "{{ hostvars['dnsmasq_server'].ansible_host }}"
    command: peer node start --peer-defaultchain=false
    state: started
    restart_policy: unless-stopped
    labels:
      org.jcloud.hyperledger: "fabric"
      org.jcloud.hyperledger.role: "fabric-peer"
  register: container_up

# blockinfile: generate restore script for fabric-peer
- name: fabric-peer | generate restore script for fabric-peer
  template: 
    src: run_new.sh.j2
    dest: /hfc-data/{{ inventory_hostname_short | lower }}/restore/run-{{ inventory_hostname_short | lower }}.sh
    mode: 0755

# cron: setup cron jobs for backup of fabric-peer
- name: fabric-peer | setup cron jobs for backup of fabric-peer
  cron:
    name: backup /hfc-data/{{ inventory_hostname_short | lower }}
    minute: "{{ ( inventory_hostname_short | hash | list | map('int',0,16) | sum ) % 60 }}"
    hour: "{{ (( inventory_hostname_short | hash | list | map('int',0,16) | sum ) % 2) + 1 }}"
    user: root
    job: "/usr/local/bin/fabric-backup.sh {{ inventory_hostname_short | lower }}"
    cron_file: "{{ inventory_hostname_short | lower }}-backup"
