---
# file: roles/fabric-orderer/tasks/main.yml
#
# copy: make sure directories exists
- name: fabric-orderer | make sure direcoties needed by fabric-orderer exists
  file:
    path: "/hfc-data/{{ inventory_hostname_short | lower }}/{{ item }}/"
    state: directory
    owner: root
    group: root
    mode: 0644
  with_items:
    - restore
    - configtx
    - data

# copy: copy crypto for fabric-orderer
- name: fabric-orderer | copy crypto for fabric-orderer
  copy:
    src: "{{ orderer_org_id | lower }}/orderers/{{ inventory_hostname_short | lower }}/"
    dest: /hfc-data/{{ inventory_hostname_short | lower }}/configtx/
    owner: root
    group: root
    mode: 0644

# template: copy env_file for fabric-orderer
- name: fabric-orderer | copy env_file for fabric-orderer
  template: 
    src: env_file.j2
    dest: /hfc-data/{{ inventory_hostname_short | lower }}/restore/env_file

# docker_container: launch fabric-orderer
- name: fabric-orderer | launch fabric-orderer
  docker_container:
    name: "{{ inventory_hostname_short | lower }}"
    hostname: "{{ inventory_hostname_short | lower }}"
    image: "{{ hfc_images.orderer.tags.0 }}"
    env_file: /hfc-data/{{ inventory_hostname_short | lower }}/restore/env_file
    volumes:
      - /hfc-data/{{ inventory_hostname_short | lower }}/configtx/:/etc/hyperledger/configtx/
      - /hfc-data/{{ inventory_hostname_short | lower }}/data/:/var/hyperledger/
    ports:
      - "0.0.0.0:{{ orderer_expose_port }}:{{ orderder_listen_port }}"
    dns_servers:
      - "{{ hostvars['dnsmasq_server'].ansible_host }}"
    command: orderer
    state: started
    restart_policy: unless-stopped
    labels:
      org.jcloud.hyperledger: "fabric"
      org.jcloud.hyperledger.role: "fabric-orderer"
  register: container_up

# blockinfile: generate restore script for fabric-orderer
- name: fabric-orderer | generate restore script for fabric-orderer
  template: 
    src: run_new.sh.j2
    dest: /hfc-data/{{ inventory_hostname_short | lower }}/restore/run-{{ inventory_hostname_short | lower }}.sh
    mode: 0755

# cron: setup cron jobs for backup of fabric-orderer
- name: fabric-orderer | setup cron jobs for backup of fabric-orderer
  cron:
    name: backup /hfc-data/{{ inventory_hostname_short | lower }}
    minute: "{{ ( inventory_hostname_short | hash | list | map('int',0,16) | sum ) % 60 }}"
    hour: "{{ (( inventory_hostname_short | hash | list | map('int',0,16) | sum ) % 2) + 1 }}"
    user: root
    job: "/usr/local/bin/fabric-backup.sh {{ inventory_hostname_short | lower }}"
    cron_file: "{{ inventory_hostname_short | lower }}-backup"
