global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_from: 'alertmanager@hfc-jcloud.local'
  smtp_smarthost: '192.168.10.7:25'
  smtp_require_tls: false
  # smtp_auth_username: 'alertmanager'
  # smtp_auth_password: 'password'
  # smtp_auth_secret: <string>
  # The auth token for Hipchat.
  # hipchat_auth_token: '1234556789'
  # Alternative host for Hipchat.
  # hipchat_url: 'https://hipchat.foobar.org/'

route:
  group_by: ['alertname', 'service']

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first 
  # notification.  
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 3h 

  # A default receiver
  receiver: 'email-to-admin'

receivers:
- name: 'email-to-admin'
  email_configs:
  - to: 'liuchenglong3@jd.com'


