---
# file: roles/dnsmasq/tasks/main.yml
#
# apt: install dnsmasq
- name: dnsmasq | install dnsmasq
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - dnsmasq
    - dnsutils

# copy: copy /etc/default/dnsmasq
- name: dnsmasq | copy /etc/default/dnsmasq
  copy:
    src: etc_default_dnsmasq
    dest: /etc/default/dnsmasq
    #backup: yes
    owner: root
    group: root
    mode: 0644 

# copy: copy /etc/dnsmasq-hfc-jcloud.conf
- name: dnsmasq | copy /etc/dnsmasq-hfc-jcloud.conf
  copy:
    src: dnsmasq-hfc-jcloud.conf
    dest: /etc/dnsmasq-hfc-jcloud.conf
    #backup: yes
    owner: root
    group: root
    mode: 0644 

# template: copy /etc/dnsmasq-hfc-jcloud.hosts
- name: dnsmasq | copy /etc/dnsmasq-hfc-jcloud.hosts
  template: 
    src: dnsmasq-hfc-jcloud.hosts.j2
    dest: /etc/dnsmasq-hfc-jcloud.hosts

# systemd: enable and start/restart dnsmasq
- name: dnsmasq | enable dnsmasq service
  systemd:
    name: dnsmasq
    enabled: yes
    state: restarted