---
# file: roles/dnsmasq/tasks/main.yml
#
# docker-image: pull image from the list
- name: dnsmasq | pull docker images
  docker_image:
    name: "{{ dnsmasq_image }}"
    state: present

# file: make sure directories exists
- name: dnsmasq | make sure direcoties needed by dnsmasq exists
  file:
    path: /monitor-server/dnsmasq/dnsmasq.d/
    state: directory
    owner: root
    group: root
    mode: 0644

# template: copy /etc/dnsmasq-jcloud-hfc.hosts
- name: dnsmasq | copy /etc/dnsmasq-jcloud-hfc.hosts
  template: 
    src: hosts.conf.j2
    dest: /monitor-server/dnsmasq/dnsmasq.d/0.hosts.conf
    owner: root
    group: root
    mode: 0644 
    force: yes

# docker-container: run dnsmasq
- name: dnsmasq | run dnsmasq
  docker_container:
    name: "{{ inventory_hostname_short|lower|replace('-','_') }}"
    hostname: "{{ inventory_hostname_short|lower|replace('-','_') }}"
    image: "{{ dnsmasq_image }}"
    volumes:
      - /monitor-server/dnsmasq/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp
    capabilities:
      - NET_ADMIN
    #network_mode: host
    labels:
      com.jcloud.group: "common"
      com.jcloud.nodetype: "dnsmasq"
    restart_policy: unless-stopped
    restart: yes
    state: started